apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: codefresh-sa
  namespace: codefresh-round3

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: codefresh-sa
  namespace: codefresh-round3
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: codefresh-sa
  namespace: codefresh-round3
roleRef:
  apiGroup: ""
  kind: Role
  name: codefresh-sa
subjects:
- kind: ServiceAccount
  name: codefresh-sa
  namespace: codefresh-round3
